### PR TITLE
Rust-sdk: Fix malformed response error when deleting ports

### PR DESCRIPTION
**Pull request by tanhakabir**
Deleting ports doesn't have any response content so we should avoid deserializing the response.

### CODE REVIEW

**Review by IlyaBiryukov — APPROVED** [review]

**Comment by tanhakabir** [comment]
@IlyaBiryukov how do you resolve the .NET pipeline error? https://devdiv.visualstudio.com/OnlineServices/_build/results?buildId=6529622&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=2b20c7d0-7587-5b0f-aadc-b456e6f0b807&l=14

**Comment by IlyaBiryukov** [comment]
It seems we need to bump our .NET core SDK version cc @jasongin

**Comment by IlyaBiryukov** [comment]
Re this error 403 Forbidden, "Unable to load the service index for source https://devdiv.pkgs.visualstudio.com/_packaging/Cascade/nuget/v3/index.json. ", I think it has something to do with the PR owner. Do you have access to that feed?

**Comment by jasongin** [comment]
@jessetrinity is working on eliminating dependencies on internal feeds.

**Comment by jasongin** [comment]
Successful delete operations generally return 204 No Content (rather than 200 OK). They may also return 404 not found if the item to be deleted was not found, and in the other language SDKs we convert that to a `false` return value rather than an exception.

**Comment by tanhakabir** [comment]
@jasongin this current implementation of throwing an error on 404s follows the rest of the sdk with tunnel deletions and so on. For the launcher simply not returning anything on success of the delete operation is fine.

**Comment by tanhakabir** [comment]
@IlyaBiryukov 
> Re this error 403 Forbidden, "Unable to load the service index for source https://devdiv.pkgs.visualstudio.com/_packaging/Cascade/nuget/v3/index.json. ", I think it has something to do with the PR owner. Do you have access to that feed?

This is all I see:
```
{"@context":{"@vocab":"http://schema.nuget.org/services#","comment":"http://www.w3.org/2000/01/rdf-schema#comment","label":"http://www.w3.org/2000/01/rdf-schema#label"},"resources":[{"@id":"https://devdiv.pkgs.visualstudio.com/_packaging/044cbcf8-f332-4cff-9cff-3a9fbe92caaa/nuget/v2/","@type":"PackagePublish/2.0.0"},{"@id":"https://devdiv.pkgs.visualstudio.com/_packaging/044cbcf8-f332-4cff-9cff-3a9fbe92caaa/nuget/v2/","@type":"LegacyGallery/2.0.0"},{"@id":"https://devdiv.pkgs.visualstudio.com/_packaging/044cbcf8-f332-4cff-9cff-3a9fbe92caaa/nuget/v3/registrations2/","@type":"RegistrationsBaseUrl/3.0.0-beta"},{"@id":"https://devdiv.pkgs.visualstudio.com/_packaging/044cbcf8-f332-4cff-9cff-3a9fbe92caaa/nuget/v3/registrations2-semver2/","@type":"RegistrationsBaseUrl/3.6.0","comment":"This base URL includes SemVer 2.0.0 packages."},{"@id":"https://devdiv.pkgs.visualstudio.com/_packaging/044cbcf8-f332-4cff-9cff-3a9fbe92caaa/nuget/v3/registrations2-semver2/","@type":"RegistrationsBaseUrl/Versioned","comment":"This base URL includes SemVer 2.0.0 packages."},{"@id":"https://devdiv.pkgs.visualstudio.com/_packaging/044cbcf8-f332-4cff-9cff-3a9fbe92caaa/nuget/v3/query2/","@type":"SearchQueryService/3.0.0-beta"},{"@id":"https://devdiv.pkgs.visualstudio.com/_packaging/044cbcf8-f332-4cff-9cff-3a9fbe92caaa/nuget/v3/flat2/","@type":"PackageBaseAddress/3.0.0"},{"@id":"https://devdiv.pkgs.visualstudio.com/","@type":"VssBaseUrl"},{"@id":"urn:uuid:044cbcf8-f332-4cff-9cff-3a9fbe92caaa","@type":"VssFeedId","label":"Cascade"},{"@id":"com.visualstudio.feeds.feedview:044cbcf8-f332-4cff-9cff-3a9fbe92caaa","@type":"VssQualifiedFeedViewId","label":"Cascade"}],"version":"3.0.0-beta"}
```

**Comment by jasongin** [comment]
> this current implementation of throwing an error on 404s follows the rest of the sdk with tunnel deletions

The C# SDK's delete APIs [convert a 404 response status to false](https://github.com/microsoft/dev-tunnels/blob/607a75253fc1219de2dee07a7a97d04078b198b2/cs/src/Management/TunnelManagementClient.cs#L341).

I see that TS/go/Java/rust SDKs do not have that behavior; I'd consider that inconsistency a bug. Typically an application doesn't consider it to be an error condition if an item to be deleted doesn't exist, often because it was already deleted concurrently.

**Comment by tanhakabir** [comment]
@jasongin Ah I see that makes sense. I can make an issue and change all the delete calls the behave the same in another PR.

**Pull request closed without merging**
